### ISSUE TITLE
problem:can't access to xml file in the server

### ISSUE THREAD

**Issue by ansar21mallouli** [nateisner/android-ads#1]
Hello,
Inside my code I put 

myAdProvider = new AdProvider.Builder(this)
                .imageServer("ftp://username:pass@aftp-server/test/test.xml") //the location of the xml file
               //code
                .start();
I am asking if  can I use ftp server  or i must use http one?

**Comment by nate-eisner** [comment]
You must use http server with my library.

**Comment by ansar21mallouli** [comment]
I have used also http server but I have the same problem 
Here is my on create function
`protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        View rootView = findViewById(R.id.adContainer);
        myAdProvider = new AdProvider.Builder(this)
                .imageServer("http://......../test.xml") //the location of the xml
                .attachTo(rootView) //root to attach to, the height
                .imageTime(5000)//in ms
                .parseTag("imagefilename") 
               .offlineUse(true) 
                .start();
        fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(getApplicationContext(),"Button Pressed",Toast.LENGTH_SHORT).show();
            }
        });
    }`
